[package]
name = "antos_multisig"
version = "1.0.0"
authors = ["Andrii Kviatkovskyi"]

[addresses]
multisig_addr = "0x490a1c503e8246ed6c60e35856ab88eb4301ac123bdb6a5b6a43e5a18985510a"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
