[package]
name = "antos_multisig"
version = "1.0.0"
authors = ["Andrii Kviatkovskyi"]

[addresses]
multisig_addr = "0x7dad8fab057bc3b3a961db831225b7d2b0daf9a85eeb8b6e0cc00b99f831b79b"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
