[package]
name = "antos_multisig"
version = "1.0.0"
authors = ["Andrii Kviatkovskyi"]

[addresses]
multisig_addr = "0xa17cd46db2b691ee042ae9edee94b64cf898f7e3c8534eb22992bd949f9a3a1e"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
